INSERT INTO players (name, elo_rating)
VALUES ('Lucas', 6.0),
    ('Sunny', 1.0),
    ('Sam', 5.0),
    ('Jackson', 5.0),
    ('Javi', 5.0),
    ('Riley', 5.0),
    ('Aidan B', 0.0),
    ('Mitch', 5.0),
    ('Malia', 4.5),
    ('Abby', 0.0),
    ('Caedon', 4.5),
    ('Andrew', 4.5),
    ('Matt W', 4.5),
    ('Aidan S', 4.0),
    ('Tim', 4.0),
    ('Nick', 4.0),
    ('Tammer', 4.0),
    ('Tommy', 3.5),
    ('Lia', 3.5),
    ('Elise', 3.5);